// Country data with ISO alpha-2 codes, names, and ISO numeric codes for TopoJSON mapping
export interface Country {
  code: string // ISO alpha-2
  name: string
  numericCode: string // ISO numeric code for TopoJSON
}

export const countries: Country[] = [
  // Middle East
  { code: 'SA', name: 'Saudi Arabia', numericCode: '682' },
  { code: 'AE', name: 'United Arab Emirates', numericCode: '784' },
  { code: 'QA', name: 'Qatar', numericCode: '634' },
  { code: 'KW', name: 'Kuwait', numericCode: '414' },
  { code: 'BH', name: 'Bahrain', numericCode: '048' },
  { code: 'OM', name: 'Oman', numericCode: '512' },
  { code: 'YE', name: 'Yemen', numericCode: '887' },
  { code: 'JO', name: 'Jordan', numericCode: '400' },
  { code: 'LB', name: 'Lebanon', numericCode: '422' },
  { code: 'IQ', name: 'Iraq', numericCode: '368' },
  { code: 'SY', name: 'Syria', numericCode: '760' },
  { code: 'PS', name: 'Palestine', numericCode: '275' },
  { code: 'EG', name: 'Egypt', numericCode: '818' },
  { code: 'TR', name: 'Turkey', numericCode: '792' },
  { code: 'IR', name: 'Iran', numericCode: '364' },
  { code: 'IL', name: 'Israel', numericCode: '376' },
  
  // North Africa
  { code: 'MA', name: 'Morocco', numericCode: '504' },
  { code: 'DZ', name: 'Algeria', numericCode: '012' },
  { code: 'TN', name: 'Tunisia', numericCode: '788' },
  { code: 'LY', name: 'Libya', numericCode: '434' },
  { code: 'SD', name: 'Sudan', numericCode: '729' },
  
  // Sub-Saharan Africa
  { code: 'NG', name: 'Nigeria', numericCode: '566' },
  { code: 'KE', name: 'Kenya', numericCode: '404' },
  { code: 'TZ', name: 'Tanzania', numericCode: '834' },
  { code: 'ZA', name: 'South Africa', numericCode: '710' },
  { code: 'ET', name: 'Ethiopia', numericCode: '231' },
  { code: 'SO', name: 'Somalia', numericCode: '706' },
  { code: 'SN', name: 'Senegal', numericCode: '686' },
  { code: 'GH', name: 'Ghana', numericCode: '288' },
  { code: 'CM', name: 'Cameroon', numericCode: '120' },
  { code: 'CI', name: "Cote d'Ivoire", numericCode: '384' },
  { code: 'UG', name: 'Uganda', numericCode: '800' },
  { code: 'ML', name: 'Mali', numericCode: '466' },
  { code: 'NE', name: 'Niger', numericCode: '562' },
  { code: 'BF', name: 'Burkina Faso', numericCode: '854' },
  { code: 'MR', name: 'Mauritania', numericCode: '478' },
  { code: 'MG', name: 'Madagascar', numericCode: '450' },
  { code: 'MZ', name: 'Mozambique', numericCode: '508' },
  { code: 'AO', name: 'Angola', numericCode: '024' },
  { code: 'ZW', name: 'Zimbabwe', numericCode: '716' },
  { code: 'RW', name: 'Rwanda', numericCode: '646' },
  { code: 'DJ', name: 'Djibouti', numericCode: '262' },
  { code: 'ER', name: 'Eritrea', numericCode: '232' },
  { code: 'GM', name: 'Gambia', numericCode: '270' },
  { code: 'GN', name: 'Guinea', numericCode: '324' },
  { code: 'SL', name: 'Sierra Leone', numericCode: '694' },
  { code: 'LR', name: 'Liberia', numericCode: '430' },
  { code: 'TD', name: 'Chad', numericCode: '148' },
  
  // South Asia
  { code: 'PK', name: 'Pakistan', numericCode: '586' },
  { code: 'IN', name: 'India', numericCode: '356' },
  { code: 'BD', name: 'Bangladesh', numericCode: '050' },
  { code: 'LK', name: 'Sri Lanka', numericCode: '144' },
  { code: 'MV', name: 'Maldives', numericCode: '462' },
  { code: 'NP', name: 'Nepal', numericCode: '524' },
  { code: 'AF', name: 'Afghanistan', numericCode: '004' },
  { code: 'BT', name: 'Bhutan', numericCode: '064' },
  
  // Southeast Asia
  { code: 'MY', name: 'Malaysia', numericCode: '458' },
  { code: 'ID', name: 'Indonesia', numericCode: '360' },
  { code: 'PH', name: 'Philippines', numericCode: '608' },
  { code: 'SG', name: 'Singapore', numericCode: '702' },
  { code: 'BN', name: 'Brunei', numericCode: '096' },
  { code: 'TH', name: 'Thailand', numericCode: '764' },
  { code: 'VN', name: 'Vietnam', numericCode: '704' },
  { code: 'KH', name: 'Cambodia', numericCode: '116' },
  { code: 'MM', name: 'Myanmar', numericCode: '104' },
  { code: 'LA', name: 'Laos', numericCode: '418' },
  
  // Central Asia
  { code: 'KZ', name: 'Kazakhstan', numericCode: '398' },
  { code: 'UZ', name: 'Uzbekistan', numericCode: '860' },
  { code: 'TM', name: 'Turkmenistan', numericCode: '795' },
  { code: 'TJ', name: 'Tajikistan', numericCode: '762' },
  { code: 'KG', name: 'Kyrgyzstan', numericCode: '417' },
  { code: 'AZ', name: 'Azerbaijan', numericCode: '031' },
  
  // Europe
  { code: 'GB', name: 'United Kingdom', numericCode: '826' },
  { code: 'FR', name: 'France', numericCode: '250' },
  { code: 'DE', name: 'Germany', numericCode: '276' },
  { code: 'NL', name: 'Netherlands', numericCode: '528' },
  { code: 'BE', name: 'Belgium', numericCode: '056' },
  { code: 'SE', name: 'Sweden', numericCode: '752' },
  { code: 'NO', name: 'Norway', numericCode: '578' },
  { code: 'IT', name: 'Italy', numericCode: '380' },
  { code: 'ES', name: 'Spain', numericCode: '724' },
  { code: 'BA', name: 'Bosnia and Herzegovina', numericCode: '070' },
  { code: 'AL', name: 'Albania', numericCode: '008' },
  { code: 'XK', name: 'Kosovo', numericCode: '-99' },
  { code: 'RS', name: 'Serbia', numericCode: '688' },
  { code: 'MK', name: 'North Macedonia', numericCode: '807' },
  { code: 'AT', name: 'Austria', numericCode: '040' },
  { code: 'CH', name: 'Switzerland', numericCode: '756' },
  { code: 'DK', name: 'Denmark', numericCode: '208' },
  { code: 'FI', name: 'Finland', numericCode: '246' },
  { code: 'PL', name: 'Poland', numericCode: '616' },
  { code: 'CZ', name: 'Czech Republic', numericCode: '203' },
  { code: 'PT', name: 'Portugal', numericCode: '620' },
  { code: 'GR', name: 'Greece', numericCode: '300' },
  { code: 'RO', name: 'Romania', numericCode: '642' },
  { code: 'BG', name: 'Bulgaria', numericCode: '100' },
  { code: 'HU', name: 'Hungary', numericCode: '348' },
  { code: 'IE', name: 'Ireland', numericCode: '372' },
  { code: 'HR', name: 'Croatia', numericCode: '191' },
  { code: 'SI', name: 'Slovenia', numericCode: '705' },
  { code: 'SK', name: 'Slovakia', numericCode: '703' },
  { code: 'UA', name: 'Ukraine', numericCode: '804' },
  { code: 'BY', name: 'Belarus', numericCode: '112' },
  { code: 'RU', name: 'Russia', numericCode: '643' },
  { code: 'ME', name: 'Montenegro', numericCode: '499' },
  { code: 'LT', name: 'Lithuania', numericCode: '440' },
  { code: 'LV', name: 'Latvia', numericCode: '428' },
  { code: 'EE', name: 'Estonia', numericCode: '233' },
  { code: 'CY', name: 'Cyprus', numericCode: '196' },
  { code: 'MT', name: 'Malta', numericCode: '470' },
  { code: 'LU', name: 'Luxembourg', numericCode: '442' },
  
  // Americas
  { code: 'US', name: 'United States', numericCode: '840' },
  { code: 'CA', name: 'Canada', numericCode: '124' },
  { code: 'BR', name: 'Brazil', numericCode: '076' },
  { code: 'AR', name: 'Argentina', numericCode: '032' },
  { code: 'MX', name: 'Mexico', numericCode: '484' },
  { code: 'CO', name: 'Colombia', numericCode: '170' },
  { code: 'CL', name: 'Chile', numericCode: '152' },
  { code: 'PE', name: 'Peru', numericCode: '604' },
  { code: 'VE', name: 'Venezuela', numericCode: '862' },
  { code: 'EC', name: 'Ecuador', numericCode: '218' },
  { code: 'UY', name: 'Uruguay', numericCode: '858' },
  { code: 'PY', name: 'Paraguay', numericCode: '600' },
  { code: 'BO', name: 'Bolivia', numericCode: '068' },
  { code: 'TT', name: 'Trinidad and Tobago', numericCode: '780' },
  { code: 'GY', name: 'Guyana', numericCode: '328' },
  { code: 'SR', name: 'Suriname', numericCode: '740' },
  { code: 'JM', name: 'Jamaica', numericCode: '388' },
  { code: 'PA', name: 'Panama', numericCode: '591' },
  { code: 'CR', name: 'Costa Rica', numericCode: '188' },
  { code: 'GT', name: 'Guatemala', numericCode: '320' },
  { code: 'HN', name: 'Honduras', numericCode: '340' },
  { code: 'SV', name: 'El Salvador', numericCode: '222' },
  { code: 'NI', name: 'Nicaragua', numericCode: '558' },
  { code: 'CU', name: 'Cuba', numericCode: '192' },
  { code: 'DO', name: 'Dominican Republic', numericCode: '214' },
  { code: 'HT', name: 'Haiti', numericCode: '332' },
  { code: 'PR', name: 'Puerto Rico', numericCode: '630' },
  
  // East Asia
  { code: 'JP', name: 'Japan', numericCode: '392' },
  { code: 'KR', name: 'South Korea', numericCode: '410' },
  { code: 'CN', name: 'China', numericCode: '156' },
  { code: 'TW', name: 'Taiwan', numericCode: '158' },
  { code: 'HK', name: 'Hong Kong', numericCode: '344' },
  { code: 'MN', name: 'Mongolia', numericCode: '496' },
  { code: 'KP', name: 'North Korea', numericCode: '408' },
  
  // Oceania
  { code: 'AU', name: 'Australia', numericCode: '036' },
  { code: 'NZ', name: 'New Zealand', numericCode: '554' },
  { code: 'FJ', name: 'Fiji', numericCode: '242' },
  { code: 'PG', name: 'Papua New Guinea', numericCode: '598' },
].sort((a, b) => a.name.localeCompare(b.name))

// Create lookup maps for quick access
export const countryByCode = new Map(countries.map(c => [c.code, c]))
export const countryByNumericCode = new Map(countries.map(c => [c.numericCode, c]))
export const numericToAlpha2 = new Map(countries.map(c => [c.numericCode, c.code]))
export const alpha2ToNumeric = new Map(countries.map(c => [c.code, c.numericCode]))
